# This project was developed with assistance from AI tools.

"""Pydantic response models for the mission planner API."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Literal, Optional

from pydantic import BaseModel, Field


class Action(BaseModel):
    """A single action/waypoint in a mission plan.

    Core waypoint fields (action_id, x, y, yaw, behavior, on_arrive) align with
    the upstream Waypoint dataclass. The description field is consumed
    by the downstream VLA model for semantic reasoning about each action.
    """

    action_id: str = Field(..., description="Human-readable waypoint identifier")
    x: float = Field(..., description="X position in meters (world frame)")
    y: float = Field(..., description="Y position in meters (world frame)")
    z: float = Field(0.0, description="Z position in meters (world frame)")
    yaw: float = Field(..., description="Yaw orientation in radians")
    behavior: Literal["walk", "climb", "descend", "stand"] = Field(
        ...,
        description="Locomotion behavior",
    )
    on_arrive: Optional[Literal["handshake", "wave", "grasp", "release"]] = Field(
        None,
        description="Skill to execute on arrival",
    )
    description: str = Field(
        ...,
        description="Natural language description of the action for VLA consumption",
    )


class ReplanCondition(BaseModel):
    """Condition under which the robot should request a new plan.

    Forward-looking: the robot client does not yet implement replanning.
    These conditions are generated by the LLM and returned for future use.
    """

    condition: str = Field(..., description="What to check")
    action_id: Optional[str] = Field(
        None,
        description="Which action this condition applies to (null = any)",
    )


class PlanResponse(BaseModel):
    """Response body for POST /v1/plan."""

    request_id: str = Field(
        default_factory=lambda: uuid.uuid4().hex,
        description="Correlation ID for tracing this request",
    )
    plan_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Plan creation time (ISO 8601, UTC)",
    )
    ttl_seconds: int = Field(
        ...,
        description="Seconds after timestamp before this plan should be considered stale",
    )
    frame_id: str = Field("world", description="Coordinate frame for all poses")
    actions: list[Action]
    scene_description: Optional[str] = Field(
        None,
        description="Scene understanding from Cosmos-Reason2 (when camera frame was provided)",
    )
    replan_conditions: list[ReplanCondition] = Field(
        default_factory=list,
        description="Conditions under which the robot should request a replan",
    )
    # Debug-only: LLM's reasoning about the plan, useful for diagnosing unexpected actions
    planning_notes: Optional[str] = Field(
        None,
        description="LLM planner reasoning notes (debug only, not consumed programmatically)",
    )


class SceneResponse(BaseModel):
    """Response body for POST /v1/scene."""

    request_id: str = Field(
        default_factory=lambda: uuid.uuid4().hex,
        description="Correlation ID for tracing this request",
    )
    scene_description: str


class ModelStatus(BaseModel):
    """Status of a single model endpoint."""

    name: str
    endpoint: str
    model: str
    available: bool
    error: Optional[str] = None


class HealthResponse(BaseModel):
    """Response body for GET /v1/health."""

    status: Literal["healthy", "degraded", "unhealthy"] = Field(...)
    version: str = "0.1.0"
    models: list[ModelStatus] = Field(default_factory=list)


class ErrorResponse(BaseModel):
    """Standard error response."""

    error: str
    detail: Optional[str] = None
